name: table_calendar
description: Highly customizable, feature-packed Flutter Calendar with gestures, animations and multiple formats.
version: 2.2.3
author: Aleksander Woźniak <aleksanderwozniak96@gmail.com>
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: "0.17.0-nullsafety.2"
  simple_gesture_detector: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
